// Generated by Fiview 0.9.10 <http://uazu.net/fiview/>.
// All generated example code below is in the public domain.
// Filter 1
// File: -i #1
// Guessed type: band-pass
//
// Frequency-response:
//   Peak gain: 1
//   Guessed 100% gain: 1
//   Regions between half-power points (70.71% response or -3.01dB):
//     250.001Hz -> 700.001Hz  (width 450Hz, midpoint 475.001Hz)
//   Regions between quarter-power points (50% response or -6.02dB):
//     204.082Hz -> 857.22Hz  (width 653.138Hz, midpoint 530.651Hz)
//
// Time-response:
//   Sampling rate is 48000Hz
//   50% complete after 48 samples (0.001s)
//   90% complete after 124 samples (0.00258333s)
//   95% complete after 146 samples (0.00304167s)
//   99% complete after 235 samples (0.00489583s)
//   99.9% complete after 345 samples (0.0071875s)
//   99.99% complete after 455 samples (0.00947917s)
//   Impulse response max deviation is at 10 samples (0.000208333s)
//   Impulse response ranges between -0.0218074 and 0.0252766
//
// Original filter:
//   x 0.00131703256325414
//   / 1 -1.90803954569008 0.914406242149202
//   x 1 -2 1
//   / 1 -1.95914164845282 0.960466191229892
//   x 1 2 1 (BpBe2/250-700)
//
// Filter descriptions:
//   BpBe2/250-700 == Bandpass Bessel filter, order 2, -3.01dB frequencies
//     250-700
//
#include <string.h>
// Example code (readable version)
float
process(register double val) {
   static double buf[4];
   register double tmp, fir, iir;
   tmp= buf[0]; memmove(buf, buf+1, 3*sizeof(double));
   // use 0.001317032563271148 below for unity gain at 100% level
   val *= 0.001317032563254142;
   iir= val+1.908039545690078*buf[0]-0.914406242149202*tmp;
   fir= iir-buf[0]-buf[0]+tmp;
   tmp= buf[1]; buf[1]= iir; val= fir;
   iir= val+1.959141648452817*buf[2]-0.9604661912298915*tmp;
   fir= iir+buf[2]+buf[2]+tmp;
   buf[3]= iir; val= fir;
   return val;
}


